### PR TITLE
Placing all pages in one padding style

### PR DESCRIPTION
**Pull request by petros-chantz**

### CODE REVIEW

**Comment by rania-chantz** [comment]
kane resolve ta conflicts prwta k meta 8a kanw review

**Comment by petros-chantz** [comment]
erwthsh egw giati den blepw oti uparxoun conflicts ?

**Comment by petros-chantz** [comment]
dhladh prwta esu prepeis na kaneis review na deis ama uparxoun conflicts meta na mou peis oti uparxoun kai na ta kanw?

**Comment by rania-chantz** [comment]
oxi kale, mporeis na ta deis, ama kaneis scroll se auth th selida katw, 8a deis oti einai gkri k leei "This branch has conflicts that must be resolved"

**Comment by petros-chantz** [comment]
hmmm 🤔 auto to blepw twra alla den hksera oti mporw na to dw prin to kaneis esu review. Nomizw den to eixa proseksei giati panta to blepw na kanei ta checks kai meta bgainei dauto

**Comment by petros-chantz** [comment]
to kanw merge dauto

**Pull request merged**
